import { Box, Button, Flex, Text, Tooltip, VStack } from '@chakra-ui/react';
import { useNavigate } from 'react-router';
import BottomButton from '../components/BottomButton';

function Landing() {
  const navigate = useNavigate();
  const onStart = () => {
    navigate('/login');
  };
  return (
    <>
      <Flex flexDirection="column" align="center" p="24px" gap="41px">
        <Text textAlign="center" fontSize="5xl">
          BARD
        </Text>
        <Text>
          BARD composes a new magical story based on your own creative
          characters with your selfies, landscapes, food, and any other daily
          photos.
        </Text>
        <Flex
          boxSizing="border-box"
          flexDirection="column"
          align="center"
          justify="center"
          padding="15px 0px"
          gap="12px"
          h="112px"
          w="calc(100vw - 48px)"
          maxW="calc(768px - 48px)"
          background="linear-gradient(274.91deg, #FFFFFF -7.57%, #FFF8DE 38.24%, #ECC94B 95.92%)"
          borderRadius="15px"
          order="2"
          zIndex="2"
        >
          <Text>Total</Text>
          <Tooltip>12,000</Tooltip>
          <Text>stories were generated by BARD</Text>
        </Flex>
        <BottomButton onClick={onStart} title="Get Started" />
      </Flex>
    </>
  );
}

export default Landing;
